package org.basuyi.xflow.core.config.model;

public interface WorkflowDefination {
	public static final String WORKFLOW_ID = "WORKFLOW_ID";		//��������ʶ
	public static final String USER_ID = "USER_ID";		//�û���ʶ
	public static final String POST_ID = "POST_ID";		//��ɫ��ʶ
	public static final String ORG_ID = "ORG_ID";		//��֯��ʶ
	public static final String START_ACTIVITY = "start";//��ʼ����
	public static final String SUBFLOW_ACTIVITY = "subflow";//�����̻���
	public static final String USER_ACTIVITY = "user";//�˹�����
	public static final String CONTEXT_KEY_USER_POLICY = "userPolicy";//�˹����ڲ���
	public static final String CONTEXT_KEY_SUBFLOW_ID = "subflowId";//�����̱�ʶ
	public static final String WORKFLOW_FINISH = "finish";//������ִ�����
	public static final String WORKFLOW_FINISH_ACTIVITY_ID = "-1";//��������ֹ���ڱ�ʶ
	public static final String DEFAULT_ACTION_TYPE = "default";//Ĭ�϶�������
	public static final String DEFAULT_RESULT_TYPE = "default";//Ĭ�Ͻ������
	public static final String DEFAULT_CONDITION_TYPE = "default";//Ĭ����������
	public static final String BEANSHELL_ACTION_TYPE = "beanshell";//beanshell��������
	public static final String BEANSHELL_CONDITION_TYPE = "beanshell";//beanshell��������
	public static final String ARG_VALUE_CLASS = "class";//class���͵Ĳ���
	public static final String CONTEXT_KEY_ARGUMENT = "argument";//class���͵Ĳ���
	public static final String CONTEXT_KEY_WF_CONTROL = "wf_control";
	public static final String CONTEXT_KEY_WF_PROCESS = "wf_process";
	public static final String WF_PROCESS_STATUS_I = "I";//���ڴ����ʼ״̬
	public static final String WF_PROCESS_STATUS_S = "S";//���ڴ���ɹ�״̬
	public static final String WF_PROCESS_STATUS_F = "F";//���ڴ���ʧ��״̬
	public static final String WF_CONFIG_EXTENTION = ".xml";//�����������ļ���׺
	public static final String CONTEXT_KEY_USER_ID = "USER_ID";		//�û���ʶ
	public static final String CONTEXT_KEY_POST_ID = "POST_ID";		//��ɫ��ʶ
	public static final String CONTEXT_KEY_ORG_ID = "ORG_ID";		//��֯��ʶ
	public static final String CONTEXT_KEY_DISPATCHER = "DISPATCHER";		//������Ա��ʶ
	public static final String CONTEXT_KEY_OPT_USER_ID = "OPT_USER_ID";		//����ʵ�ʴ�����Ա��ʶ
	public static final String CONTEXT_KEY_DISPATCH_STATUS = "DISPATCH_STATUS";		//����״̬
	public static final String USER_POLICY_RBAC = "rbac";//���ڽ�ɫ���û�����
	public static final String USER_POLICY_UESR_INPUT = "user-input";//�����û�ָ����Ա��ʽ���û�����
	public static final String DISPATCHER = "DISPATCHER";//���������Ա��ʶ
	public static final String OPT_USER_ID = "OPT_USER_ID";//ʵ�ʴ�����Ա��ʶ
	public static final String IS_SUBFLOW = "IS_SUBFLOW";//�Ƿ�������
	public static final String UPPER_WORKFLOW = "UPPER_WORKFLOW";//�ϲ㹤��������
	public static final String UPPER_WF_PARAMS = "UPPER_WF_PARAMS";//�ϲ㹤����������
	public static final String WORKFLOW_CONTEXT = "WORKFLOW_CONTEXT";//�����������Ķ���
	public static final String CONTEXT_KEY_WORKFLOW_ID = "WORKFLOW_ID";//��������ʶ
	public static final String UPPER_ACTIVITY_ID = "UPPER_ACTIVITY_ID";//�ϲ㹤������ǰִ�л���
	public static final String UPPER_WORKFLOW_ID = "UPPER_WORKFLOW_ID";//�ϲ㹤������ʶ
	public static final String CONTEXT_KEY_UPPER_ACTIVITY_ID = "CONTEXT_KEY_UPPER_ACTIVITY_ID";//�ϲ㹤������ǰִ�л���
	public static final String CONTEXT_KEY_UPPER_WORKFLOW_ID = "CONTEXT_KEY_UPPER_WORKFLOW_ID";//�ϲ㹤������ʶ
	public static final String WF_CONFIG_DIR = "workflow";//�����������ļ�Ŀ¼
	public static final String DIR_DELIMITER = "/";
	public static final String IN_PARAMS = "IN_PARAMS";//������ԭʼ�������
	public static final String USER_ENTRY = "USER_ENTRY";//�û����
	public static final String WF_INST_ID = "WF_INST_ID";//������ʵ����ʶ
	public static final String WF_PROCESS_SEQ = "WF_PROCESS_SEQ";//������ִ����ˮ��
	public static final String WF_CONFIG_XML = "xml";//XML��������
	public static final String WF_CONFIG_DB = "database";//���ݿ���������
	public static final String WF_CONFIG_POLICY = "workflow_config_policy";//���������ò���
	public static final String CONTEXT_KEY_WF_SERVICE_NOTX = "CONTEXT_KEY_WF_SERVICE_NOTX";
	public static final String CONTEXT_KEY_WF_SERVICE_TX = "CONTEXT_KEY_WF_SERVICE_TX";
	public static final String CONTEXT_KEY_APP_CONTEXT = "ApplicationContext";
}
